# Generated by Django 2.0.5 on 2018-07-10 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsmodel',
            options={'ordering': ['-pub_time']},
        ),
    ]
