# Generated by Django 2.0.5 on 2018-07-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180724_1752'),
        ('news', '0007_auto_20180721_1015'),
    ]

    operations = [
    ]
