# Generated by Django 2.0.5 on 2018-07-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20180725_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='thumbnail',
            new_name='cover_url',
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
