"""
Django settings for xfz project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'lpmk-2(xxqgz+q3@x(9db7n9y6j$=*f+-w^afp8i#-iql48(vb'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1','118.126.108.129']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.news',
    'apps.cms',
    'apps.course',
    'apps.xfzauth',
    'password_reset',# 密码重置应用
    'apps.ueditor',# 富文本编辑器
    'rest_framework',# REST API接口pytho
    'debug_toolbar',#Django-Debug-Toolbar
]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'xfz.urls'

# Usermodel
AUTH_USER_MODEL = 'xfzauth.User'
# 重置密码邮箱配置

EMAIL_HOST = 'smtp.163.com'
EMAIL_HOST_USER = "wwlzxukeqing@163.com"
EMAIL_HOST_PASSWORD='12354abcs' #密码
EMAIL_PORT = 25
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = "wwlzxukeqing@163.com"
# 邮件信息后台显示
EMAIL_BACKEND= "django.core.mail.backends.smtp.EmailBackend"


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'front','templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'apps.xfzauth.context_processor.frontuser'
            ],
            # 模板中不用load即可使用static标签加载静态文件
            'builtins':['django.templatetags.static']
        },
    },
]

WSGI_APPLICATION = 'xfz.wsgi.application'

# cache
# memcached 的配置
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'LOCATION': '118.126.108.129:11211',
    }
}
# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'xfz',
        'HOST':'127.0.0.1',
        'PORT':'3306',
        'USER':'root',
        'PASSWORD':'123456'
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True


USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

# 配置静态文件的路径
STATICFILES_DIRS = [
    os.path.join(BASE_DIR,'front','dist')
]

# 文件大小
# DATA_UPLOAD_MAX_NUMBER_FIELDS = 10240

# 上传文件夹设置
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'


# upload相关配置
UEDITOR_CONFIG_PATH = os.path.join(BASE_DIR,'front','dist','ueditor','config.json')

UEDITOR_QINIU_ACCESS_KEY = "qHC83yOGuWzpW9hW6Wt2JEQseqKIq0Z4G970ALR9"
UEDITOR_QINIU_SECRET_KEY = "cnCE1B7T3Jj5tqG1rqisAD2KY6Jz4zSioQCZ_L__"
UEDITOR_QINIU_BUCKET_NAME = "dxxfz"
UEDITOR_QINIU_DOMAIN = "http://pbci7ji9t.bkt.clouddn.com/"

UEDITOR_UPLOAD_TO_QINIU = True

# 上传到本地服务器
UEDITOR_UPLOAD_TO_SERVER = False
UEDITOR_UPLOAD_PATH = os.path.join(BASE_DIR,'media')

# 每页默认显示新闻数量
PERPAGE_NEWS_COUNT = 2

# Django-Debug-Toolbar相关配置
INTERNAL_IPS = ['127.0.0.1']
DEBUG_TOOLBAR_CONFIG = {
    'JQUERY_URL':'http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js'
}

DEBUG_TOOLBAR_PANELS = [
    # 'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    # 'debug_toolbar.panels.settings.SettingsPanel',
    # 'debug_toolbar.panels.headers.HeadersPanel',
    # 'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    # 'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    # 'debug_toolbar.panels.templates.TemplatesPanel',
    # 'debug_toolbar.panels.cache.CachePanel',
    # 'debug_toolbar.panels.signals.SignalsPanel',
    # 'debug_toolbar.panels.logging.LoggingPanel',
    # 'debug_toolbar.panels.redirects.RedirectsPanel',
]

#百度云配置
BAIDU_CLOUD_USER_ID = "7f3b33ce9d1a4e2ca9ad149908cf4e15"
BAIDU_CLOUD_USER_KEY = "a53798e34c72478c"